stargazers_count = 3
license_url = ""
doctype = "default"
owner = "mschauer"
installs = true
license = "Other"
version = "0.3.2"
description = "Gaussian distributions as state variables and for uncertainty quantification with Unitful"

[[contributors]]
name = "mschauer"
contributions = 28
[[contributors]]
name = "cstjean"
contributions = 11
[[contributors]]
name = "yakir12"
contributions = 1
[[contributors]]
name = "femtocleaner[bot]"
contributions = 1
