stargazers_count = 0
license_url = ""
doctype = "default"
owner = "JuliaSmoothOptimizers"
installs = true
license = "Other"
version = "0.3.0"
description = "Approximate Minimum Degree Ordering in Julia"

[[contributors]]
name = "dpo"
contributions = 30
[[contributors]]
name = "abelsiqueira"
contributions = 6
[[contributors]]
name = "staticfloat"
contributions = 1
[[contributors]]
name = "tkelman"
contributions = 1
[[contributors]]
name = "masuday"
contributions = 1
