stargazers_count = 1
license_url = "https://api.github.com/licenses/mit"
doctype = "default"
owner = "kdyrhage"
installs = true
license = "MIT License"
version = "0.1.0"
description = ""

[[contributors]]
name = "kdyrhage"
contributions = 46
