stargazers_count = 40
license_url = ""
doctype = "default"
owner = "vtjnash"
installs = true
license = "Other"
version = "1.2.0"
description = "Posix-compliant file name pattern matching"

[[contributors]]
name = "vtjnash"
contributions = 11
[[contributors]]
name = "hayd"
contributions = 3
[[contributors]]
name = "EQt"
contributions = 2
[[contributors]]
name = "JonathanAnderson"
contributions = 1
[[contributors]]
name = "NHDaly"
contributions = 1
[[contributors]]
name = "shashi"
contributions = 1
[[contributors]]
name = "tkelman"
contributions = 1
[[contributors]]
name = "jmkuhn"
contributions = 1
