stargazers_count = 13
license_url = ""
doctype = "default"
owner = "joshday"
installs = true
license = "Other"
version = "0.9.2"
description = "Base types for OnlineStats."

[[contributors]]
name = "joshday"
contributions = 233
