stargazers_count = 37
license_url = ""
doctype = "default"
owner = "Keno"
installs = true
license = "Other"
version = "0.2.1"
description = "Abstract julia interfaces for working with trees"

[[contributors]]
name = "Keno"
contributions = 42
[[contributors]]
name = "PallHaraldsson"
contributions = 4
[[contributors]]
name = "yuyichao"
contributions = 4
[[contributors]]
name = "JeffBezanson"
contributions = 3
[[contributors]]
name = "femtocleaner[bot]"
contributions = 2
[[contributors]]
name = "porterjamesj"
contributions = 1
[[contributors]]
name = "habemus-papadum"
contributions = 1
[[contributors]]
name = "StefanKarpinski"
contributions = 1
[[contributors]]
name = "scls19fr"
contributions = 1
