stargazers_count = 4
license_url = ""
doctype = "default"
owner = "marcpabst"
installs = true
license = "Other"
version = "0.1.0"
description = "Provides a Simple Way to Calculate ANOVAs From Fitted Linear Models."

[[contributors]]
name = "marcpabst"
contributions = 57
[[contributors]]
name = "Nosferican"
contributions = 1
