stargazers_count = 9
license_url = ""
doctype = "default"
owner = "JuliaGraphs"
installs = true
license = "Other"
version = "0.4.0"
description = "Graph IO functionality for various formats."

[[contributors]]
name = "sbromberger"
contributions = 38
[[contributors]]
name = "simonschoelly"
contributions = 11
[[contributors]]
name = "bicycle1885"
contributions = 2
[[contributors]]
name = "andreasnoack"
contributions = 1
[[contributors]]
name = "nickeubank"
contributions = 1
[[contributors]]
name = "waldyrious"
contributions = 1
