stargazers_count = 1
license_url = "https://api.github.com/licenses/lgpl-3.0"
doctype = "default"
owner = "ma-laforge"
installs = true
license = "GNU Lesser General Public License v3.0"
version = "0.3.0"
description = "Pure-Julia .psf writer"

[[contributors]]
name = "ma-laforge"
contributions = 10
