stargazers_count = 16
doctype = "default"
installs = true
version = "0.4.0"
description = "Julia wrapper around nettle cryptographic hashing/encryption library providing MD5, SHA1, SHA2 hashing and HMAC functionality, as well as AES encryption/decryption"
