stargazers_count = 0
license_url = "https://api.github.com/licenses/mit"
doctype = "default"
owner = "JeffreySarnoff"
installs = true
license = "MIT License"
version = "0.0.1"
description = ""

[[contributors]]
name = "JeffreySarnoff"
contributions = 38
