language: julia
os:
  - linux
services:
  - xvfb
julia:
  - 1.3
  - 1.4
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly
before_install:
  - sudo apt-get install ruby bundler cmake pkg-config git libssl-dev
  - gem install --no-ri --no-rdoc licensee
