language: julia
os:
  - linux
julia:
  - 1.1
  - 1.2
  - 1.3
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly
    - julia: 1.1 # entropy errors...
before_install:
  - sudo apt-get install ruby bundler cmake pkg-config git libssl-dev
  - gem install --no-ri --no-rdoc licensee
