name = "DocumentationGenerator"
uuid = "8f0d3306-d70b-5309-b898-24bb6ab47850"
repo = "https://github.com/pfitzseb/DocumentationGenerator.jl.git"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
