stargazers_count = 5
license_url = ""
doctype = "default"
owner = "ChrisRackauckas"
installs = true
license = "Other"
version = "0.1.0"
description = "Provides an array type designed for efficient appending and ease of use."

[[contributors]]
name = "ChrisRackauckas"
contributions = 27
[[contributors]]
name = "gragusa"
contributions = 8
[[contributors]]
name = "tkelman"
contributions = 1
