stargazers_count = 8
license_url = ""
doctype = "default"
owner = "wdebeaum"
installs = true
license = "Other"
version = "1.0.0"
description = "Define a Parsing Expression Grammar via a macro and abuse of Julia syntax."

[[contributors]]
name = "wdebeaum"
contributions = 31
[[contributors]]
name = "staticfloat"
contributions = 1
[[contributors]]
name = "tkelman"
contributions = 1
