stargazers_count = 69
license_url = ""
doctype = "default"
owner = "JuliaDiffEq"
installs = true
license = "Other"
version = "4.21.1"
description = "DiffEq solvers for ordinary differential equations"

[[contributors]]
name = "ChrisRackauckas"
contributions = 1368
[[contributors]]
name = "YingboMa"
contributions = 456
[[contributors]]
name = "MSeeker1340"
contributions = 244
[[contributors]]
name = "sipah00"
contributions = 119
[[contributors]]
name = "devmotion"
contributions = 113
[[contributors]]
name = "ranocha"
contributions = 67
[[contributors]]
name = "kanav99"
contributions = 25
[[contributors]]
name = "dextorious"
contributions = 16
[[contributors]]
name = "tkf"
contributions = 14
[[contributors]]
name = "deeepeshthakur"
contributions = 13
[[contributors]]
name = "tyfff"
contributions = 10
[[contributors]]
name = "saurabhkgp21"
contributions = 10
[[contributors]]
name = "gabrielgellner"
contributions = 9
[[contributors]]
name = "timkittel"
contributions = 7
[[contributors]]
name = "dgan181"
contributions = 5
[[contributors]]
name = "EllarBooher"
contributions = 5
[[contributors]]
name = "jagot"
contributions = 5
[[contributors]]
name = "rudrasohan"
contributions = 4
[[contributors]]
name = "arnav-t"
contributions = 4
[[contributors]]
name = "femtocleaner[bot]"
contributions = 3
[[contributors]]
name = "staticfloat"
contributions = 2
[[contributors]]
name = "baggepinnen"
contributions = 2
[[contributors]]
name = "Datseris"
contributions = 2
[[contributors]]
name = "JonasIsensee"
contributions = 2
[[contributors]]
name = "ScottPJones"
contributions = 2
[[contributors]]
name = "tkelman"
contributions = 2
[[contributors]]
name = "tkoolen"
contributions = 2
[[contributors]]
name = "antoine-levitt"
contributions = 1
[[contributors]]
name = "blegat"
contributions = 1
[[contributors]]
name = "dawbarton"
contributions = 1
[[contributors]]
name = "korsbo"
contributions = 1
[[contributors]]
name = "Vaibhavdixit02"
contributions = 1
