stargazers_count = 2
license_url = ""
doctype = "default"
owner = "JuliaString"
installs = true
license = "Other"
version = "0.1.2"
description = "Wrapper for PCRE2 libraries (8, 16, 32-bit)"

[[contributors]]
name = "ScottPJones"
contributions = 21
