stargazers_count = 14
license_url = ""
doctype = "default"
owner = "JuliaGeo"
installs = true
license = "Other"
version = "0.4.0"
description = "Utilities for working with GeoJSON data in Julia"

[[contributors]]
name = "yeesian"
contributions = 26
[[contributors]]
name = "visr"
contributions = 20
[[contributors]]
name = "garborg"
contributions = 5
[[contributors]]
name = "AndyGreenwell"
contributions = 2
[[contributors]]
name = "jbn"
contributions = 1
