stargazers_count = 1
license_url = ""
doctype = "default"
owner = "JuliaGraphs"
installs = true
license = "Other"
version = "0.1.0"
description = "Graph500 benchmarks written in Julia using LightGraphs"

[[contributors]]
name = "somil55"
contributions = 37
[[contributors]]
name = "sbromberger"
contributions = 4
