stargazers_count = 1
license_url = ""
doctype = "default"
owner = "staticfloat"
installs = true
license = "Other"
version = "0.2.0"
description = "Julia package to interface with Ogg containers and streams"

[[contributors]]
name = "staticfloat"
contributions = 30
[[contributors]]
name = "omus"
contributions = 4
[[contributors]]
name = "ssfrr"
contributions = 2
