stargazers_count = 0
license_url = "https://api.github.com/licenses/mit"
doctype = "default"
owner = "attractivechaos"
installs = true
license = "MIT License"
version = "0.1.0"
description = "Command-line argument parsing with a similar API to Python's getopt"

[[contributors]]
name = "attractivechaos"
contributions = 10
