stargazers_count = 5
license_url = ""
doctype = "default"
owner = "JuliaComputing"
installs = true
license = "Other"
version = "0.2.0"
description = "A Julia AMQP (Advanced Message Queuing Protocol) / RabbitMQ Client."

[[contributors]]
name = "tanmaykm"
contributions = 50
[[contributors]]
name = "quinnj"
contributions = 18
[[contributors]]
name = "scls19fr"
contributions = 1
