stargazers_count = 3
license_url = "https://api.github.com/licenses/mit"
doctype = "default"
owner = "eschnett"
installs = true
license = "MIT License"
version = "1.0.3"
description = "A Julia implementation of the Advanced Scientific Data Format (ASDF)"

[[contributors]]
name = "eschnett"
contributions = 41
