stargazers_count = 3
license_url = ""
doctype = "default"
owner = "maximsch2"
installs = true
license = "Other"
version = "0.0.1"
description = "Open Biomedical Ontologies (OBO) file parser"

[[contributors]]
name = "maximsch2"
contributions = 25
[[contributors]]
name = "alyst"
contributions = 20
