stargazers_count = 4
license_url = ""
doctype = "default"
owner = "chkwon"
installs = true
license = "Other"
version = "0.5.1"
description = "provides a Julia wrapper for the PATH Solver for solving mixed complementarity problems"

[[contributors]]
name = "chkwon"
contributions = 137
[[contributors]]
name = "rdeits"
contributions = 9
[[contributors]]
name = "staticfloat"
contributions = 3
[[contributors]]
name = "AndradeTiago"
contributions = 1
[[contributors]]
name = "jrevels"
contributions = 1
