stargazers_count = "13"
doctype = "default"
installs = true
version = "0.9.3"
description = ":calendar: A highly optimized Business Days calculator written in Julia language. Also known as Working Days calculator."
