stargazers_count = 6
license_url = "https://api.github.com/licenses/mit"
doctype = "default"
owner = "ma-laforge"
installs = true
license = "MIT License"
version = "0.3.0"
description = "Fine control over numeric output: Scientific/Engineering/SI-notation +UTF8"

[[contributors]]
name = "ma-laforge"
contributions = 21
[[contributors]]
name = "tkelman"
contributions = 2
