stargazers_count = 0
license_url = ""
doctype = "default"
owner = "staticfloat"
installs = true
license = "Other"
version = "0.3.1"
description = "Object File (ELF, MachO, COFF/PE, etc...) parser for Julia"

[[contributors]]
name = "staticfloat"
contributions = 39
[[contributors]]
name = "Keno"
contributions = 25
[[contributors]]
name = "tkelman"
contributions = 4
[[contributors]]
name = "quinnj"
contributions = 2
