stargazers_count = 3
license_url = ""
doctype = "default"
owner = "JuliaGeometry"
installs = true
license = "Other"
version = "0.3.0"
description = "Algorithms for packing problems"

[[contributors]]
name = "SimonDanisch"
contributions = 19
[[contributors]]
name = "sjkelly"
contributions = 4
