stargazers_count = 3
license_url = ""
doctype = "default"
owner = "tkluck"
installs = true
license = "Other"
version = "0.2.1"
description = "Finite fields for Julia"

[[contributors]]
name = "tkluck"
contributions = 59
