stargazers_count = 5
doctype = "default"
installs = true
version = "0.1.0"
description = "The U.S. Committee on Extension to the Standard Atmosphere (COESA) atmosphere model, also known as the U.S. Standard Atmosphere, 1976."
