stargazers_count = 6
license_url = ""
doctype = "default"
owner = "gcalderone"
installs = true
license = "Other"
version = "1.0.0"
description = "Julia interface to Gnuplot"

[[contributors]]
name = "gcalderone"
contributions = 74
