stargazers_count = 0
license_url = ""
doctype = "default"
owner = "simonfxr"
installs = true
license = "Other"
version = "0.1.0"
description = "Julia Optionals Package"

[[contributors]]
name = "simonfxr"
contributions = 4
