stargazers_count = 1
license_url = "https://api.github.com/licenses/mit"
doctype = "default"
owner = "zgornel"
installs = true
license = "MIT License"
version = "0.1.1"
description = "Julia interface to GloVe"

[[contributors]]
name = "zgornel"
contributions = 16
