stargazers_count = 0
license_url = "https://api.github.com/licenses/mit"
doctype = "default"
owner = "scheinerman"
installs = true
license = "MIT License"
version = "0.1.1"
description = "Abstract lattice functions meet and join, with symbols \\wedge and \\vee"

[[contributors]]
name = "scheinerman"
contributions = 7
