stargazers_count = 0
doctype = "default"
installs = true
version = "0.1.1"
description = "Exercism.jl provides tooling and utility functions to solve exercises on exercism.io in interactive environments such as IJulia notebooks."
