stargazers_count = 2
license_url = "https://api.github.com/licenses/mit"
doctype = "default"
owner = "GlenHertz"
installs = true
license = "MIT License"
version = "0.2.0"
description = "Simple Julia grep for iterables/containers"

[[contributors]]
name = "GlenHertz"
contributions = 6
