stargazers_count = "5"
doctype = "default"
installs = true
version = "0.5.0"
description = "Utility for developers to help define DataDeps registration blocks, for reusing existing Data with DataDeps.jl"
