stargazers_count = "0"
doctype = "real"
installs = true
version = "0.0.1"
description = "A Julia package to send SMS (Short Message Service) using BulkSMS API https://scls19fr.github.io/BulkSMS.jl/dev"
