stargazers_count = 2
license_url = ""
doctype = "default"
owner = "samoconnor"
installs = true
license = "Other"
version = "0.5.0"
description = "AWS SQS Simple Queue Service interface for Julia"

[[contributors]]
name = "samoconnor"
contributions = 73
[[contributors]]
name = "ararslan"
contributions = 2
[[contributors]]
name = "tkelman"
contributions = 2
[[contributors]]
name = "jingpengw"
contributions = 1
