stargazers_count = 7
license_url = ""
doctype = "default"
owner = "randyzwitch"
installs = true
license = "Other"
version = "0.4.0"
description = "Julia package for fun or non-standard color palettes"

[[contributors]]
name = "randyzwitch"
contributions = 29
[[contributors]]
name = "staticfloat"
contributions = 1
[[contributors]]
name = "femtocleaner[bot]"
contributions = 1
