stargazers_count = 140
license_url = ""
doctype = "default"
owner = "jheinen"
installs = true
license = "Other"
version = "0.37.0"
description = "Plotting for Julia based on GR, a framework for visualisation applications"

[[contributors]]
name = "jheinen"
contributions = 472
[[contributors]]
name = "barche"
contributions = 2
[[contributors]]
name = "mteser"
contributions = 2
[[contributors]]
name = "tkelman"
contributions = 2
[[contributors]]
name = "FlorianRhiem"
contributions = 2
[[contributors]]
name = "eugene"
contributions = 1
[[contributors]]
name = "fredrikekre"
contributions = 1
[[contributors]]
name = "joshday"
contributions = 1
[[contributors]]
name = "mpastell"
contributions = 1
[[contributors]]
name = "hessammehr"
contributions = 1
[[contributors]]
name = "dalum"
contributions = 1
[[contributors]]
name = "pfitzseb"
contributions = 1
[[contributors]]
name = "ThoAppelsin"
contributions = 1
[[contributors]]
name = "cnliao"
contributions = 1
[[contributors]]
name = "goropikari"
contributions = 1
[[contributors]]
name = "machakann"
contributions = 1
[[contributors]]
name = "v-i-s-h"
contributions = 1
