stargazers_count = 0
license_url = "https://api.github.com/licenses/mit"
doctype = "default"
owner = "dalum"
installs = true
license = "MIT License"
version = "0.1.0"
description = "A package for making concrete instances of abstract types"

[[contributors]]
name = "dalum"
contributions = 5
