stargazers_count = 55
doctype = "default"
installs = true
version = "2.3.0"
description = "A Julia package for defining and working with linear maps, also known as linear transformations or linear operators acting on vectors. The only requirement for a LinearMap is that it can act on a vector (by multiplication) efficiently."
