stargazers_count = 1
license_url = ""
doctype = "default"
owner = "RalphAS"
installs = true
license = "Other"
version = "0.2.0"
description = "Julia package for Schur decomposition of matrices with generic element types"

[[contributors]]
name = "RalphAS"
contributions = 12
