stargazers_count = 0
license_url = ""
doctype = "default"
owner = "ellisvalentiner"
installs = true
license = "Other"
version = "0.1.0"
description = "Unofficial Julia client for the Google Maps/Places API"

[[contributors]]
name = "ellisvalentiner"
contributions = 11
