stargazers_count = 6
license_url = ""
doctype = "default"
owner = "Julia-i18n"
installs = true
license = "Other"
version = "0.2.0"
description = "i18n for Julia"

[[contributors]]
name = "garrison"
contributions = 28
